### ISSUE TITLE
neo4j-admin import not working

### ISSUE THREAD

**Issue by banned007** [bitnami/bitnami-docker-neo4j#4] opened 2019-08-07 16:11 UTC
**Description**

I am having problems deploying a database in a container based of this image, the weird thing is that it works on my computer, I've tried everything, and I'm out of options and ideas.. the error is from java.io it has something to do with the permissions granted to the default user of the container (that's what i assume from the output message of the exception thrown), and I am new to this and there is no information on the internet of this error message so I'm posting it here.

**Steps to reproduce the issue:**

1. Create the container from this image using Azure in c#
2. upload a CVS database to the container just created (to the file-share)
3. use the `neo4j-admin import` command
![import](https://user-images.githubusercontent.com/27454269/62638260-4c1fd480-b8fa-11e9-9764-8d98fb96f19a.PNG)

**Describe the results you received:**

```Available resources:
  Total machine memory: 7.77 GB
  Free machine memory: 5.44 GB
  Max heap memory : 1.04 GB
  Processors: 1
  Configured max memory: 6.05 GB
  High-IO: false

Import starting 2019-08-07 15:47:37.507+0000
  Estimated number of nodes: 12.82 k
  Estimated number of node properties: 49.51 k
  Estimated number of relationships: 47.49 k
  Estimated number of relationship properties: 47.54 k
  Estimated disk space usage: 6.51 MB
  Estimated required memory usage: 1020.17 MB

InteractiveReporterInteractions command list (end with ENTER):
  c: Print more detailed information about current stage
  i: Print more detailed information

(1/4) Node import 2019-08-07 15:47:37.604+0000
  Estimated number of nodes: 12.82 k
  Estimated disk space usage: 2.83 MB
  Estimated required memory usage: 1020.17 MB
.......... .......... .......... .......... ..........   5% ∆1s 616ms
.......... .......... .......... .......... ..........  10% ∆63ms
.......... .......... .......... .......... ..........  15% ∆10ms
.......... .......... .......... .......... ..........  20% ∆9ms
.......... .......... .......... .......... ..........  25% ∆9ms
.......... .......... .......... .......... ..........  30% ∆11ms
.......... .......... .......... .......... ..........  35% ∆1ms
.......... .......... .......... .......... ..........  40% ∆1ms
.......... .......... .......... .......... ..........  45% ∆1ms
.......... .......... .......... .......... ..........  50% ∆2ms
.......... .......... .......... .......... ..........  55% ∆2ms
.......... .......... .......... .......... ..........  60% ∆1ms
.......... .......... .......... .......... ..........  65% ∆1ms
.......... .......... .......... .......... ..........  70% ∆1ms
.......... .......... .......... .......... ..........  75% ∆1ms
.......... .......... .......... .......... ..........  80% ∆1ms
.......... .......... .......... .......... ..........  85% ∆1ms
.......... .......... .......... .......... ..........  90% ∆0ms
.......... .......... .......... .......... ..........  95% ∆3ms
.......... .......... .......... .......... .......... 100% ∆1ms


IMPORT FAILED in 3s 792ms.
Data statistics is not available.
Peak memory usage: 0.00 B
Import error: java.io.IOException: java.util.concurrent.ExecutionException: java.io.UncheckedIOException: java.io.IOException: Permission denied
Caused by:java.io.IOException: java.util.concurrent.ExecutionException: java.io.UncheckedIOException: java.io.IOException: Permission denied
java.lang.RuntimeException: java.io.IOException: java.util.concurrent.ExecutionException: java.io.UncheckedIOException: java.io.IOException: Permission denied
        at org.neo4j.unsafe.impl.batchimport.store.PageCacheFlusher.halt(PageCacheFlusher.java:80)
        at org.neo4j.unsafe.impl.batchimport.store.BatchingNeoStores.stopFlushingPageCache(BatchingNeoStores.java:444)
        at org.neo4j.unsafe.impl.batchimport.ImportLogic.importNodes(ImportLogic.java:259)
        at org.neo4j.unsafe.impl.batchimport.ParallelBatchImporter.doImport(ParallelBatchImporter.java:90)
        at org.neo4j.tooling.ImportTool.doImport(ImportTool.java:585)
        at org.neo4j.commandline.dbms.CsvImporter.doImport(CsvImporter.java:128)
        at org.neo4j.commandline.dbms.ImportCommand.execute(ImportCommand.java:236)
        at org.neo4j.commandline.admin.AdminTool.execute(AdminTool.java:127)
        at org.neo4j.commandline.admin.AdminTool.main(AdminTool.java:51)
        Suppressed: java.lang.RuntimeException: java.io.IOException: java.util.concurrent.ExecutionException: java.io.UncheckedIOException: java.io.IOException: Permission denied
                at org.neo4j.unsafe.impl.batchimport.store.PageCacheFlusher.halt(PageCacheFlusher.java:80)
                at org.neo4j.unsafe.impl.batchimport.store.BatchingNeoStores.stopFlushingPageCache(BatchingNeoStores.java:444)
                at org.neo4j.unsafe.impl.batchimport.store.BatchingNeoStores.close(BatchingNeoStores.java:375)
                at org.neo4j.unsafe.impl.batchimport.ParallelBatchImporter.doImport(ParallelBatchImporter.java:99)
                ... 5 more
        Caused by: java.io.IOException: java.util.concurrent.ExecutionException: java.io.UncheckedIOException: java.io.IOException: Permission denied
                at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.flushAllPagesParallel(MuninnPageCache.java:645)
                at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.flushAndForce(MuninnPageCache.java:601)
                at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.flushAndForce(MuninnPageCache.java:581)
                at org.neo4j.unsafe.impl.batchimport.store.PageCacheFlusher.run(PageCacheFlusher.java:53)
        Caused by: java.util.concurrent.ExecutionException: java.io.UncheckedIOException: java.io.IOException: Permission denied
                at java.util.concurrent.FutureTask.report(FutureTask.java:122)
                at java.util.concurrent.FutureTask.get(FutureTask.java:192)
                at org.neo4j.kernel.impl.scheduler.PooledJobHandle.waitTermination(PooledJobHandle.java:59)
                at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.flushAllPagesParallel(MuninnPageCache.java:641)
                ... 3 more
        Caused by: java.io.UncheckedIOException: java.io.IOException: Permission denied
                at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.lambda$flushAllPagesParallel$0(MuninnPageCache.java:631)
                at org.neo4j.kernel.impl.scheduler.ThreadPool.lambda$submit$0(ThreadPool.java:57)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
        Caused by: java.io.IOException: Permission denied
                at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
                at sun.nio.ch.FileDispatcherImpl.writev(FileDispatcherImpl.java:72)
                at sun.nio.ch.IOUtil.write(IOUtil.java:148)
                at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:239)
                at java.nio.channels.FileChannel.write(FileChannel.java:414)
                at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.lockPositionWriteVectorAndRetryIfInterrupted(SingleFilePageSwapper.java:546)
                at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.writePositionedVectoredToFileChannel(SingleFilePageSwapper.java:514)
                at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.write(SingleFilePageSwapper.java:492)
                at org.neo4j.io.pagecache.impl.muninn.MuninnPagedFile.vectoredFlush(MuninnPagedFile.java:456)
                at org.neo4j.io.pagecache.impl.muninn.MuninnPagedFile.doFlushAndForceInternal(MuninnPagedFile.java:429)
                at org.neo4j.io.pagecache.impl.muninn.MuninnPagedFile.flushAndForceInternal(MuninnPagedFile.java:352)
                at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.flushFile(MuninnPageCache.java:655)
                at org.neo4j.io.pagecache.impl.muninn.MuninnPageCache.lambda$flushAllPagesParallel$0(MuninnPageCache.java:627)
                ... 6 more
        [CIRCULAR REFERENCE:java.io.IOException: java.util.concurrent.ExecutionException: java.io.UncheckedIOException: java.io.IOException: Permission denied]

WARNING Import failed. The store files in /bitnami/neo4j/data/databases/graph.db are left as they are, although they are likely in an unusable state. Starting a database on these store files will likely fail or observe inconsistent records so start at your own risk or delete the store manually
unexpected error: java.io.IOException: java.util.concurrent.ExecutionException: java.io.UncheckedIOException: java.io.IOException: Permission denied
```

**Describe the results you expected:**

import successful

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens only with big databases

**Version**

- Output of `docker version`:

N/A

- Output of `docker info`:

N/A

- Output of `docker-compose version` (if applicable):

N/A

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Azure container 2gb memory.

**Comment by marcosbc** [comment] 2019-08-08 14:19
Hi @banned007, due to the complexity of debugging your issue (it depends on huge databases), as you mention it works in your computer, could you check if this is happening because of running as a non-root user?

You can do it with the following change to your docker-compose file:

```
--- docker-compose.yml	2019-08-08 16:17:35.028594695 +0200
+++ docker-compose.yml	2019-08-08 16:14:09.989964968 +0200
@@ -2,6 +2,7 @@
 services:
   neo4j:
     image: 'bitnami/neo4j:3'
+    user: root
     ports:
       - '7474:7474'
       - '7473:7473'
```

If it does not work, could you provide us with an approximate size of your backups/CSVs so we can try to reproduce this issue on our side?

**Comment by banned007** [comment] 2019-08-08 15:55
Hi @marcosbc, and thanks for your reply, I'm gonna try doing that to the .yml file next (not sure how to atm since I am using the Azure marketplace for the image registry), but I managed to come with a workaround the first problem; I installed Neo4j in the same windows VM where the Web API is running and made a batch file that runs ```neo4j-admin import ...```, then I move the resulting graph.db content to the file-share that the container is going to use. This solves the import issue, but another problem arises (with the ```java.io.IOException``` exception), this is an the same issue posted in the ```neo4j/neo4j``` GitHub repository I will link it so you can have a look. [https://github.com/neo4j/neo4j/issues/12077](url)

**Comment by banned007** [comment] 2019-08-08 20:55
modifying the docker-compose file did not work either.. this is what I get when I make the container with the pushed image:
![Capture](https://user-images.githubusercontent.com/27454269/62737207-794caf80-b9ec-11e9-95ba-169df06d2878.PNG)

Note that both queries are made in the same session.

**Comment by marcosbc** [comment] 2019-08-09 14:48
Since it is not working on your side, could you provide more information on the size of the different files so we can try to reproduce this on our own? Since you mention this does not happen with small databases.

Thanks!

**Comment by banned007** [comment] 2019-08-09 17:03
yeah, the ones that work are relatively small, but in absolute terms, they are all pretty small (bellow 50MBs).

![Capture](https://user-images.githubusercontent.com/27454269/62795707-93da6380-ba94-11e9-8ac5-eecec521d03f.PNG)

![Capture](https://user-images.githubusercontent.com/27454269/62795965-3397f180-ba95-11e9-94e7-c45a99dc1f7a.PNG)

**Comment by banned007** [comment] 2019-08-09 20:26
I found a workaround, the problem is with the file-share that I was using (apparently is set to be read-only), and I cannot change the setting for it to be read and write.. what I did is:

1. being logged in the container as any user (1001), create a directory ```/tmp/bitcopy/``` where the ```/bitnami/neo4j/data/``` directory will be copied.
2. copy the database directory. 
3. stop the neo4j service with ```neo4j stop```.
4. delete the link directory from ```/opt/bitnami/neo4j/data```.
5. copy the directory ```/tmp/bitcopy/data/``` to ```/opt/bitnami/neo4j/data/```
6. give all permissions to the copied directory with ```chmod -r 777 /opt/bitnami/neo4j/data```.
7. delete the ```/tmp/bitcopy/data/``` directory.
start neo4j service with ```neo4j start```.

Thanks for your time @marcosbc :), I would love that you gave an option to make a copy instead of a link of the file-share in the ```/opt/bitnami/neo4j/``` directory to overcome this problem more easily..

**Comment by marcosbc** [comment] 2019-08-12 08:05
Hi @banned007, that's great to hear. I'm going to close this issue.

As for the file share, it must be read-write or it will eventually fail, either during the initialization or when running. I'm sorry it took you so long to realize, usually it fails for users when initializing but in your case you already had the data.

Unfortunately having a read-only share is a scenario we cannot support, mainly because it's where the data for the application is stored when stopping/starting the container.

**Closed by marcosbc** 2019-08-12 08:05 UTC
